// =============================================================================
// TD Engine — TDScript JS Code Generator Implementation (Tier 4)
// =============================================================================
#include "codegen_js.h"
#include <sstream>

namespace td::tdscript {

CodeGenJs::CodeGenJs() {}

void CodeGenJs::emit(const std::string& s) { m_out += s; }
void CodeGenJs::emitIndent() { for (int i = 0; i < m_indent; i++) m_out += "  "; }
void CodeGenJs::emitLine(const std::string& s) { emitIndent(); m_out += s; m_out += "\n"; }
void CodeGenJs::newline() { m_out += "\n"; }

std::string CodeGenJs::generate(const NodePtr& module) {
    m_out.clear();
    m_indent = 0;
    emitLine("// Auto-generated by TDScript compiler (target: js). Do not edit by hand.");
    emitLine("'use strict';");
    newline();
    emitModule(module);
    return m_out;
}

void CodeGenJs::emitModule(const NodePtr& n) {
    for (const auto& child : n->children) {
        switch (child->kind) {
            case NodeKind::ImportStmt: emitImport(child); break;
            case NodeKind::StructDecl: emitStruct(child); break;
            case NodeKind::ClassDecl:  emitClass(child); break;
            default: break;
        }
    }
}

void CodeGenJs::emitImport(const NodePtr& n) {
    // `import "engine/networking";` → `require('engine/networking');`
    // In browser context, this is a no-op (the runtime is pre-loaded).
    // In Node, it requires the module.
    emitLine("try { require('" + n->text + "'); } catch (e) { /* browser: pre-loaded */ }");
}

void CodeGenJs::emitStruct(const NodePtr& n) {
    // struct → emitted as a plain JS class with a constructor
    emitLine("global." + n->text + " = class " + n->text + " {");
    pushIndent();
    emitLine("constructor() {");
    pushIndent();
    for (const auto& f : n->children) {
        if (f->kind == NodeKind::FieldDecl) {
            emitIndent();
            m_out += "this." + f->text + " = ";
            if (f->initExpr) emitExpression(f->initExpr);
            else m_out += defaultInitFor(f->type ? f->type->text : "auto");
            m_out += ";\n";
        }
    }
    popIndent();
    emitLine("}");
    popIndent();
    emitLine("};");
    newline();
}

void CodeGenJs::emitClass(const NodePtr& n) {
    emitLine("global." + n->text + " = class " + n->text + " {");
    pushIndent();
    emitLine("constructor() {");
    pushIndent();
    // Initialize fields
    for (const auto& m : n->children) {
        if (m->kind == NodeKind::FieldDecl) {
            emitField(m, /*isClassMember=*/true);
        }
    }
    popIndent();
    emitLine("}");
    newline();
    // Methods + RPC registration
    for (const auto& m : n->children) {
        if (m->kind == NodeKind::MethodDecl) {
            emitMethod(m);
        }
    }
    popIndent();
    emitLine("};");
    newline();
    // Collect replicated field names for the registration call
    std::vector<std::string> replFields;
    for (const auto& m : n->children) {
        if (m->kind == NodeKind::FieldDecl && m->isReplicated) {
            replFields.push_back(m->text);
        }
    }
    // Register RPCs at module load
    for (const auto& m : n->children) {
        if (m->kind == NodeKind::MethodDecl && m->rpcMode != RpcMode::None) {
            const char* modeStr = (m->rpcMode == RpcMode::Reliable) ? "reliable" : "unreliable";
            emitLine("if (typeof __td_rpc_register === 'function') {");
            pushIndent();
            emitLine("__td_rpc_register('" + n->text + "', '" + m->text + "', '" + std::string(modeStr) +
                     "', function(instance, args) { return instance." + m->text + ".apply(instance, args); });");
            popIndent();
            emitLine("}");
        }
    }
    // Register replicated fields at module load
    if (!replFields.empty()) {
        emitLine("if (typeof __td_repl_register === 'function') {");
        pushIndent();
        std::string fieldsJson = "[";
        for (size_t i = 0; i < replFields.size(); i++) {
            if (i > 0) fieldsJson += ", ";
            fieldsJson += "\"" + replFields[i] + "\"";
        }
        fieldsJson += "]";
        emitLine("__td_repl_register('" + n->text + "', " + fieldsJson + ");");
        popIndent();
        emitLine("}");
    }
    newline();
}

void CodeGenJs::emitField(const NodePtr& n, bool isClassMember) {
    if (!isClassMember) return;
    // `replicated Type name [= init];`
    // For non-replicated: simple assignment in constructor.
    // For replicated: use Object.defineProperty to trap writes.
    if (n->isReplicated) {
        // We can't easily use defineProperty in the constructor for every instance
        // (it would be slow and re-define the property). Instead, we:
        //   1. Set a private backing field this._name = init
        //   2. Define getters/setters on the prototype ONCE (in module load).
        // For simplicity here, we set the backing field in the constructor.
        emitIndent();
        m_out += "this._" + n->text + " = ";
        if (n->initExpr) emitExpression(n->initExpr);
        else m_out += defaultInitFor(n->type ? n->type->text : "auto");
        m_out += ";  // replicated (backing field)\n";
    } else {
        emitIndent();
        m_out += "this." + n->text + " = ";
        if (n->initExpr) emitExpression(n->initExpr);
        else m_out += defaultInitFor(n->type ? n->type->text : "auto");
        m_out += ";\n";
    }
}

void CodeGenJs::emitMethod(const NodePtr& n) {
    // signature: methodName(params) {
    std::string sig = n->text + "(";
    for (size_t i = 0; i < n->children.size(); i++) {
        if (i > 0) sig += ", ";
        sig += n->children[i]->text;  // parameter name
    }
    sig += ") {";
    emitLine(sig);
    pushIndent();
    if (n->thenBranch) emitBlock(n->thenBranch);
    popIndent();
    emitLine("}");
    newline();
}

void CodeGenJs::emitBlock(const NodePtr& n) {
    if (!n || n->kind != NodeKind::Block) return;
    for (const auto& stmt : n->children) {
        emitStatement(stmt);
    }
}

void CodeGenJs::emitStatement(const NodePtr& n) {
    if (!n) return;
    switch (n->kind) {
        case NodeKind::Block: {
            emitLine("{");
            pushIndent();
            emitBlock(n);
            popIndent();
            emitLine("}");
            break;
        }
        case NodeKind::VarDeclStmt: emitVarDecl(n); break;
        case NodeKind::IfStmt: emitIf(n); break;
        case NodeKind::ForStmt: emitFor(n); break;
        case NodeKind::WhileStmt: emitWhile(n); break;
        case NodeKind::ReturnStmt: emitReturn(n); break;
        case NodeKind::BreakStmt: emitLine("break;"); break;
        case NodeKind::ContinueStmt: emitLine("continue;"); break;
        case NodeKind::ExprStmt: {
            emitIndent();
            emitExpression(n->initExpr);
            m_out += ";\n";
            break;
        }
        default: break;
    }
}

void CodeGenJs::emitVarDecl(const NodePtr& n) {
    // `var/const/type name [= init];` → `let name = init;` or `let name;`
    emitIndent();
    m_out += "let " + n->text;
    if (n->initExpr) {
        m_out += " = ";
        emitExpression(n->initExpr);
    }
    m_out += ";\n";
}

void CodeGenJs::emitIf(const NodePtr& n) {
    emitIndent();
    m_out += "if (";
    emitExpression(n->cond);
    m_out += ") ";
    if (n->thenBranch) {
        if (n->thenBranch->kind == NodeKind::Block) {
            m_out += "{\n";
            pushIndent();
            emitBlock(n->thenBranch);
            popIndent();
            emitLine("}");
        } else {
            m_out += "\n";
            pushIndent();
            emitStatement(n->thenBranch);
            popIndent();
        }
    }
    if (n->elseBranch) {
        if (n->thenBranch->kind == NodeKind::Block) {
            m_out = m_out.substr(0, m_out.size() - 1);  // remove trailing newline after }
            m_out += " else ";
        } else {
            emitIndent();
            m_out += "else ";
        }
        if (n->elseBranch->kind == NodeKind::Block) {
            m_out += "{\n";
            pushIndent();
            emitBlock(n->elseBranch);
            popIndent();
            emitLine("}");
        } else if (n->elseBranch->kind == NodeKind::IfStmt) {
            // else-if: emit on same line
            // Pop the indent we just added so emitIf doesn't double-indent
            popIndent();
            emitIf(n->elseBranch);
            pushIndent();
        } else {
            m_out += "\n";
            pushIndent();
            emitStatement(n->elseBranch);
            popIndent();
        }
    }
}

void CodeGenJs::emitFor(const NodePtr& n) {
    // for (init; cond; step) body
    emitIndent();
    m_out += "for (";
    if (n->lhs) {
        // var decl or expr stmt — we want the inner part without the trailing ;
        std::string saved = m_out;
        m_out.clear();
        if (n->lhs->kind == NodeKind::VarDeclStmt) emitVarDecl(n->lhs);
        else { emitExpression(n->lhs->initExpr); m_out += ";"; }
        // strip trailing newline + ;
        std::string inner = m_out;
        m_out = saved;
        // remove trailing ";\n"
        size_t end = inner.find(";\n");
        if (end != std::string::npos) inner = inner.substr(0, end);
        m_out += inner + "; ";
    } else {
        m_out += "; ";
    }
    if (n->cond) emitExpression(n->cond);
    m_out += "; ";
    if (n->step) emitExpression(n->step);
    m_out += ") ";
    if (n->thenBranch) {
        if (n->thenBranch->kind == NodeKind::Block) {
            m_out += "{\n";
            pushIndent();
            emitBlock(n->thenBranch);
            popIndent();
            emitLine("}");
        } else {
            m_out += "\n";
            pushIndent();
            emitStatement(n->thenBranch);
            popIndent();
        }
    }
}

void CodeGenJs::emitWhile(const NodePtr& n) {
    emitIndent();
    m_out += "while (";
    emitExpression(n->cond);
    m_out += ") ";
    if (n->thenBranch) {
        if (n->thenBranch->kind == NodeKind::Block) {
            m_out += "{\n";
            pushIndent();
            emitBlock(n->thenBranch);
            popIndent();
            emitLine("}");
        } else {
            m_out += "\n";
            pushIndent();
            emitStatement(n->thenBranch);
            popIndent();
        }
    }
}

void CodeGenJs::emitReturn(const NodePtr& n) {
    emitIndent();
    m_out += "return";
    if (n->initExpr) {
        m_out += " ";
        emitExpression(n->initExpr);
    }
    m_out += ";\n";
}

void CodeGenJs::emitExpression(const NodePtr& n) {
    if (!n) return;
    switch (n->kind) {
        case NodeKind::IntLiteral:
        case NodeKind::FloatLiteral:
            m_out += n->text;
            break;
        case NodeKind::StringLiteral:
            m_out += "\"";
            for (char c : n->text) {
                switch (c) {
                    case '"': m_out += "\\\""; break;
                    case '\\': m_out += "\\\\"; break;
                    case '\n': m_out += "\\n"; break;
                    case '\r': m_out += "\\r"; break;
                    case '\t': m_out += "\\t"; break;
                    default: m_out += c;
                }
            }
            m_out += "\"";
            break;
        case NodeKind::BoolLiteral: m_out += n->boolVal ? "true" : "false"; break;
        case NodeKind::NullLiteral: m_out += "null"; break;
        case NodeKind::Identifier: emitIdentifier(n); break;
        case NodeKind::MemberAccess: emitMemberAccess(n); break;
        case NodeKind::IndexAccess: emitIndexAccess(n); break;
        case NodeKind::Call: emitCall(n); break;
        case NodeKind::Binary: emitBinary(n); break;
        case NodeKind::Unary: emitUnary(n); break;
        case NodeKind::Assign: emitAssign(n); break;
        case NodeKind::CompoundAssign: emitCompoundAssign(n); break;
        default: m_out += "/* unknown expr */"; break;
    }
}

void CodeGenJs::emitIdentifier(const NodePtr& n) {
    // Map known TDScript type names to runtime equivalents
    if (n->text == "Vector3") { m_out += "Vector3"; return; }
    if (n->text == "Math") { m_out += "Math"; return; }
    if (n->text == "Log") { m_out += "Log"; return; }
    if (n->text == "Network") { m_out += "Network"; return; }
    if (n->text == "Physics") { m_out += "Physics"; return; }
    if (n->text == "this") { m_out += "this"; return; }
    m_out += n->text;
}

void CodeGenJs::emitMemberAccess(const NodePtr& n) {
    emitExpression(n->lhs);
    m_out += ".";
    m_out += n->text;
}

void CodeGenJs::emitIndexAccess(const NodePtr& n) {
    emitExpression(n->lhs);
    m_out += "[";
    emitExpression(n->rhs);
    m_out += "]";
}

void CodeGenJs::emitCall(const NodePtr& n) {
    emitExpression(n->lhs);
    m_out += "(";
    for (size_t i = 0; i < n->children.size(); i++) {
        if (i > 0) m_out += ", ";
        emitExpression(n->children[i]);
    }
    m_out += ")";
}

void CodeGenJs::emitBinary(const NodePtr& n) {
    m_out += "(";
    emitExpression(n->lhs);
    m_out += " ";
    m_out += n->text;
    m_out += " ";
    emitExpression(n->rhs);
    m_out += ")";
}

void CodeGenJs::emitUnary(const NodePtr& n) {
    m_out += "(";
    m_out += n->text;
    emitExpression(n->lhs);
    m_out += ")";
}

void CodeGenJs::emitAssign(const NodePtr& n) {
    // If the LHS is a member access to a replicated field (this._name),
    // we'd ideally route through __td_repl_write. But detecting that at
    // codegen time requires symbol tracking. For now, we rely on the
    // runtime's defineProperty setter to intercept writes (set up at
    // module load). For non-replicated fields, plain assignment works.
    emitExpression(n->lhs);
    m_out += " = ";
    emitExpression(n->rhs);
}

void CodeGenJs::emitCompoundAssign(const NodePtr& n) {
    emitExpression(n->lhs);
    m_out += " ";
    m_out += n->text;
    m_out += " ";
    emitExpression(n->rhs);
}

std::string CodeGenJs::jsTypeFor(const std::string& tdType) {
    if (tdType == "int32" || tdType == "uint32" || tdType == "int64" ||
        tdType == "uint64" || tdType == "float" || tdType == "double") return "number";
    if (tdType == "bool") return "boolean";
    if (tdType == "string") return "string";
    if (tdType == "auto") return "any";
    return tdType;  // custom types (Vector3, struct names)
}

std::string CodeGenJs::defaultInitFor(const std::string& tdType) {
    if (tdType == "int32" || tdType == "uint32" || tdType == "int64" ||
        tdType == "uint64" || tdType == "float" || tdType == "double") return "0";
    if (tdType == "bool") return "false";
    if (tdType == "string") return "\"\"";
    if (tdType == "void" || tdType == "auto") return "null";
    // Custom type: call its constructor (e.g., new Vector3())
    return "null";
}

} // namespace td::tdscript
