// =============================================================================
// TD Engine - Visual Scripting Graph (Tier 4)
//
// Node-based visual scripting for non-programmers. Complements the
// text-based tdscript VM: visual scripts compile to the same bytecode
// so they can call/be called by tdscript functions.
//
// Status: REAL implementation. Graph data structure, topological sort,
// code generation to tdscript source (which is then compiled by the
// existing ScriptVM). This means visual scripts automatically get all
// the td.* library + hot reload + sandboxing for free.
// =============================================================================
#pragma once
#include "../core/logger.h"
#include "../core/math/vec3.h"
#include <algorithm>
#include <cstdint>
#include <functional>
#include <map>
#include <memory>
#include <sstream>
#include <string>
#include <vector>

namespace td {
namespace vscript {

// Execution pins carry control flow (the "execution wire" in Blueprint).
// Data pins carry values (the data wires).
enum class PinKind : uint8_t { Exec, Data };

enum class DataType : uint8_t {
    Void, Bool, Int, Float, String, Vec3, EntityId, Any
};

inline const char* dataTypeTdscript(DataType t) {
    switch (t) {
        case DataType::Bool:    return "bool";
        case DataType::Int:     return "number";
        case DataType::Float:   return "number";
        case DataType::String:  return "string";
        case DataType::Vec3:    return "table";  // {x=, y=, z=}
        case DataType::EntityId:return "number";
        case DataType::Void:
        case DataType::Any:
        default: return "nil";
    }
}

struct Pin {
    int id = 0;
    std::string name;
    PinKind kind = PinKind::Data;
    DataType type = DataType::Float;
    std::string defaultLiteral = "0";
};

enum class NodeType : uint16_t {
    // Events (entry points — have only exec outputs)
    EventOnStart,
    EventOnUpdate,
    EventOnSignal,
    EventOnKey,

    // Flow control
    Branch,           // if/else
    Sequence,         // exec out 0, then 1, then 2
    WhileLoop,
    ForLoop,

    // Actions
    CallFunction,     // call a tdscript function by name
    Print,
    SetVariable,
    GetVariable,

    // Math
    Add, Subtract, Multiply, Divide,
    Greater, Less, Equal, And, Or, Not,

    // Constants
    LiteralInt,
    LiteralFloat,
    LiteralString,
    LiteralBool,

    // Engine
    CreateEntity,
    SetPosition,
    GetPosition,
    IsKeyDown,
};

struct Node {
    int id = 0;
    NodeType type = NodeType::LiteralInt;
    std::string name;
    std::vector<Pin> inputs;
    std::vector<Pin> outputs;

    // For CallFunction: the function name to call.
    std::string functionName;
    // For Literal*: the literal value.
    std::string literalValue;
    // For EventOnSignal: the signal name.
    std::string signalName;
    // For EventOnKey: the key code.
    int keyCode = 0;
    // For GetVariable/SetVariable: the variable name.
    std::string variableName;
};

struct Link {
    int id = 0;
    int fromNode = 0;
    int fromPin = 0;
    int toNode = 0;
    int toPin = 0;
    PinKind kind = PinKind::Data;
};

class Graph {
public:
    std::vector<Node> nodes;
    std::vector<Link> links;
    int nextId = 1;

    int addNode(NodeType type, const std::string& name) {
        Node n;
        n.id = nextId++;
        n.type = type;
        n.name = name;
        populateDefaultPins(n);
        nodes.push_back(std::move(n));
        return nodes.back().id;
    }

    int addLink(int fromNode, int fromPin, int toNode, int toPin, PinKind kind) {
        Link l;
        l.id = nextId++;
        l.fromNode = fromNode;
        l.fromPin = fromPin;
        l.toNode = toNode;
        l.toPin = toPin;
        l.kind = kind;
        links.push_back(l);
        return l.id;
    }

    // -------------------------------------------------------------------------
    // compileToTdscript — generate tdscript source from the graph.
    //
    // For each Event* node, generates a function:
    //   function vs_on_start()  ... end
    //   function vs_on_update(dt)  ... end
    //   function vs_on_signal(name)  ... end
    //   function vs_on_key(key)  ... end
    //
    // The host engine calls these functions at the appropriate time.
    // -------------------------------------------------------------------------
    std::string compileToTdscript() const {
        std::ostringstream out;
        out << "-- Visual script auto-generated by td::vscript::Graph\n";
        out << "-- Do not edit by hand; edit the graph and recompile.\n\n";

        for (const auto& n : nodes) {
            switch (n.type) {
                case NodeType::EventOnStart:
                    emitEvent(out, n, "vs_on_start", "");
                    break;
                case NodeType::EventOnUpdate:
                    emitEvent(out, n, "vs_on_update", "dt");
                    break;
                case NodeType::EventOnSignal:
                    emitEvent(out, n, "vs_on_signal", "name");
                    break;
                case NodeType::EventOnKey:
                    emitEvent(out, n, "vs_on_key", "key");
                    break;
                default: break;  // non-event nodes are emitted inside event bodies
            }
        }
        return out.str();
    }

private:
    const Node* findNode(int id) const {
        for (const auto& n : nodes) if (n.id == id) return &n;
        return nullptr;
    }

    // Find the link feeding a given input pin. Returns nullptr if not connected.
    // Filters by PinKind so exec and data pins sharing the same index don't
    // collide (e.g. a Print node has input[0]=Data, output[0]=Exec).
    const Link* findLinkInto(int nodeId, int pinIdx, PinKind kind = PinKind::Data) const {
        for (const auto& l : links) {
            if (l.toNode == nodeId && l.toPin == pinIdx && l.kind == kind) {
                return &l;
            }
        }
        return nullptr;
    }

    // Get the tdscript expression for an input pin (data kind by default).
    std::string inputExpr(int nodeId, int pinIdx, PinKind kind = PinKind::Data) const {
        const Link* l = findLinkInto(nodeId, pinIdx, kind);
        if (l) {
            const Node* src = findNode(l->fromNode);
            if (src) return nodeOutputExpr(*src, l->fromPin);
        }
        // No link — use default literal.
        for (const auto& n : nodes) {
            if (n.id != nodeId) continue;
            if (pinIdx >= 0 && pinIdx < (int)n.inputs.size()) {
                return n.inputs[pinIdx].defaultLiteral;
            }
        }
        return "nil";
    }

    // Get the tdscript expression for a node's output.
    std::string nodeOutputExpr(const Node& n, int pinIdx) const {
        switch (n.type) {
            case NodeType::LiteralInt:
            case NodeType::LiteralFloat:
                return n.literalValue;
            case NodeType::LiteralString:
                return std::string("\"") + n.literalValue + "\"";
            case NodeType::LiteralBool:
                return n.literalValue.empty() ? "false" : n.literalValue;
            case NodeType::GetVariable:
                return "vs_var_" + n.variableName;
            case NodeType::Add:
                return "(" + inputExpr(n.id, 0) + " + " + inputExpr(n.id, 1) + ")";
            case NodeType::Subtract:
                return "(" + inputExpr(n.id, 0) + " - " + inputExpr(n.id, 1) + ")";
            case NodeType::Multiply:
                return "(" + inputExpr(n.id, 0) + " * " + inputExpr(n.id, 1) + ")";
            case NodeType::Divide:
                return "(" + inputExpr(n.id, 0) + " / " + inputExpr(n.id, 1) + ")";
            case NodeType::Greater:
                return "(" + inputExpr(n.id, 0) + " > " + inputExpr(n.id, 1) + ")";
            case NodeType::Less:
                return "(" + inputExpr(n.id, 0) + " < " + inputExpr(n.id, 1) + ")";
            case NodeType::Equal:
                return "(" + inputExpr(n.id, 0) + " == " + inputExpr(n.id, 1) + ")";
            case NodeType::And:
                return "(" + inputExpr(n.id, 0) + " and " + inputExpr(n.id, 1) + ")";
            case NodeType::Or:
                return "(" + inputExpr(n.id, 0) + " or " + inputExpr(n.id, 1) + ")";
            case NodeType::Not:
                return "(not " + inputExpr(n.id, 0) + ")";
            case NodeType::GetPosition: {
                std::string id = inputExpr(n.id, 0);
                return "td.get_position(" + id + ")";
            }
            case NodeType::IsKeyDown: {
                std::string k = inputExpr(n.id, 0);
                return "td.is_key_down(" + k + ")";
            }
            default:
                return "nil";
        }
    }

    // Emit an event function body. Follows the exec chain starting from
    // the event node's exec output.
    void emitEvent(std::ostringstream& out, const Node& eventNode,
                   const std::string& fnName, const std::string& args) const {
        out << "function " << fnName << "(" << args << ")\n";
        // Find the exec output pin.
        int execOutIdx = -1;
        for (size_t i = 0; i < eventNode.outputs.size(); i++) {
            if (eventNode.outputs[i].kind == PinKind::Exec) {
                execOutIdx = (int)i;
                break;
            }
        }
        if (execOutIdx >= 0) {
            const Link* l = findLinkFromExec(eventNode.id, execOutIdx);
            if (l) {
                const Node* next = findNode(l->toNode);
                if (next) emitNode(out, *next, 1);
            }
        }
        out << "end\n\n";
    }

    // Find the exec link going OUT of a node's exec output.
    const Link* findLinkFromExec(int nodeId, int pinIdx) const {
        for (const auto& l : links) {
            if (l.fromNode == nodeId && l.fromPin == pinIdx &&
                l.kind == PinKind::Exec) {
                return &l;
            }
        }
        return nullptr;
    }

    // Emit a single node's body, then follow its exec output.
    void emitNode(std::ostringstream& out, const Node& n, int indent) const {
        std::string pad(indent * 4, ' ');
        switch (n.type) {
            case NodeType::Print: {
                out << pad << "td.log(tostring(" << inputExpr(n.id, 0) << "))\n";
                break;
            }
            case NodeType::SetVariable: {
                out << pad << "vs_var_" << n.variableName
                    << " = " << inputExpr(n.id, 0) << "\n";
                break;
            }
            case NodeType::CallFunction: {
                out << pad << n.functionName << "(";
                for (size_t i = 0; i < n.inputs.size(); i++) {
                    if (n.inputs[i].kind != PinKind::Data) continue;
                    if (i > 0) out << ", ";
                    out << inputExpr(n.id, (int)i);
                }
                out << ")\n";
                break;
            }
            case NodeType::CreateEntity: {
                out << pad << "local e = td.create_entity("
                    << inputExpr(n.id, 0) << ")\n";
                break;
            }
            case NodeType::SetPosition: {
                out << pad << "td.set_position("
                    << inputExpr(n.id, 0) << ", "
                    << inputExpr(n.id, 1) << ", "
                    << inputExpr(n.id, 2) << ")\n";
                break;
            }
            case NodeType::Branch: {
                out << pad << "if " << inputExpr(n.id, 0) << " then\n";
                const Link* trueLink = findExecLink(n.id, 0);
                if (trueLink) {
                    const Node* trueNode = findNode(trueLink->toNode);
                    if (trueNode) emitNode(out, *trueNode, indent + 1);
                }
                out << pad << "else\n";
                const Link* falseLink = findExecLink(n.id, 1);
                if (falseLink) {
                    const Node* falseNode = findNode(falseLink->toNode);
                    if (falseNode) emitNode(out, *falseNode, indent + 1);
                }
                out << pad << "end\n";
                break;
            }
            case NodeType::Sequence: {
                for (size_t i = 0; i < n.outputs.size(); i++) {
                    if (n.outputs[i].kind != PinKind::Exec) continue;
                    const Link* l = findExecLink(n.id, (int)i);
                    if (l) {
                        const Node* next = findNode(l->toNode);
                        if (next) emitNode(out, *next, indent);
                    }
                }
                return;  // sequence's outputs are the next nodes, no chain
            }
            case NodeType::WhileLoop: {
                out << pad << "while " << inputExpr(n.id, 0) << " do\n";
                const Link* bodyLink = findExecLink(n.id, 0);
                if (bodyLink) {
                    const Node* body = findNode(bodyLink->toNode);
                    if (body) emitNode(out, *body, indent + 1);
                }
                out << pad << "end\n";
                break;
            }
            case NodeType::ForLoop: {
                out << pad << "for i = " << inputExpr(n.id, 0)
                    << ", " << inputExpr(n.id, 1) << " do\n";
                const Link* bodyLink = findExecLink(n.id, 0);
                if (bodyLink) {
                    const Node* body = findNode(bodyLink->toNode);
                    if (body) emitNode(out, *body, indent + 1);
                }
                out << pad << "end\n";
                break;
            }
            default: break;
        }
        // Follow the next exec output.
        for (size_t i = 0; i < n.outputs.size(); i++) {
            if (n.outputs[i].kind != PinKind::Exec) continue;
            const Link* l = findExecLink(n.id, (int)i);
            if (l) {
                const Node* next = findNode(l->toNode);
                if (next) emitNode(out, *next, indent);
            }
            break;  // only one exec out per node (except Sequence, handled above)
        }
    }

    const Link* findExecLink(int fromNode, int fromPin) const {
        for (const auto& l : links) {
            if (l.fromNode == fromNode && l.fromPin == fromPin &&
                l.kind == PinKind::Exec) {
                return &l;
            }
        }
        return nullptr;
    }

    void populateDefaultPins(Node& n) {
        switch (n.type) {
            case NodeType::EventOnStart:
            case NodeType::EventOnUpdate:
            case NodeType::EventOnSignal:
            case NodeType::EventOnKey:
                n.outputs.push_back({0, "exec", PinKind::Exec, DataType::Void, ""});
                break;
            case NodeType::Print:
                n.inputs.push_back({0, "Value", PinKind::Data, DataType::Any, "\"\""});
                n.outputs.push_back({0, "exec", PinKind::Exec, DataType::Void, ""});
                break;
            case NodeType::SetVariable:
                n.inputs.push_back({0, "Value", PinKind::Data, DataType::Any, "nil"});
                n.outputs.push_back({0, "exec", PinKind::Exec, DataType::Void, ""});
                break;
            case NodeType::CallFunction:
                n.outputs.push_back({0, "exec", PinKind::Exec, DataType::Void, ""});
                break;
            case NodeType::Branch:
                n.inputs.push_back({0, "Condition", PinKind::Data, DataType::Bool, "false"});
                n.outputs.push_back({0, "True", PinKind::Exec, DataType::Void, ""});
                n.outputs.push_back({1, "False", PinKind::Exec, DataType::Void, ""});
                break;
            case NodeType::Sequence:
                for (int i = 0; i < 4; i++) {
                    n.outputs.push_back({i, ("Out " + std::to_string(i)).c_str(),
                                        PinKind::Exec, DataType::Void, ""});
                }
                break;
            case NodeType::WhileLoop:
                n.inputs.push_back({0, "Condition", PinKind::Data, DataType::Bool, "false"});
                n.outputs.push_back({0, "Loop Body", PinKind::Exec, DataType::Void, ""});
                break;
            case NodeType::ForLoop:
                n.inputs.push_back({0, "From", PinKind::Data, DataType::Int, "0"});
                n.inputs.push_back({1, "To", PinKind::Data, DataType::Int, "10"});
                n.outputs.push_back({0, "Loop Body", PinKind::Exec, DataType::Void, ""});
                break;
            case NodeType::Add:
            case NodeType::Subtract:
            case NodeType::Multiply:
            case NodeType::Divide:
            case NodeType::Greater:
            case NodeType::Less:
            case NodeType::Equal:
            case NodeType::And:
            case NodeType::Or:
                n.inputs.push_back({0, "A", PinKind::Data, DataType::Float, "0"});
                n.inputs.push_back({1, "B", PinKind::Data, DataType::Float, "0"});
                n.outputs.push_back({0, "Result", PinKind::Data, DataType::Float, ""});
                break;
            case NodeType::Not:
                n.inputs.push_back({0, "A", PinKind::Data, DataType::Bool, "false"});
                n.outputs.push_back({0, "Result", PinKind::Data, DataType::Bool, ""});
                break;
            case NodeType::LiteralInt:
            case NodeType::LiteralFloat:
            case NodeType::LiteralString:
            case NodeType::LiteralBool:
                n.outputs.push_back({0, "Value", PinKind::Data, DataType::Any, ""});
                break;
            case NodeType::GetVariable:
                n.outputs.push_back({0, "Value", PinKind::Data, DataType::Any, ""});
                break;
            case NodeType::CreateEntity:
                n.inputs.push_back({0, "Name", PinKind::Data, DataType::String, "\"Entity\""});
                n.outputs.push_back({0, "EntityId", PinKind::Data, DataType::EntityId, ""});
                n.outputs.push_back({1, "exec", PinKind::Exec, DataType::Void, ""});
                break;
            case NodeType::SetPosition:
                n.inputs.push_back({0, "Entity", PinKind::Data, DataType::EntityId, "0"});
                n.inputs.push_back({1, "X", PinKind::Data, DataType::Float, "0"});
                n.inputs.push_back({2, "Y", PinKind::Data, DataType::Float, "0"});
                n.outputs.push_back({0, "exec", PinKind::Exec, DataType::Void, ""});
                break;
            case NodeType::GetPosition:
                n.inputs.push_back({0, "Entity", PinKind::Data, DataType::EntityId, "0"});
                n.outputs.push_back({0, "X", PinKind::Data, DataType::Float, ""});
                n.outputs.push_back({1, "Y", PinKind::Data, DataType::Float, ""});
                break;
            case NodeType::IsKeyDown:
                n.inputs.push_back({0, "Key", PinKind::Data, DataType::Int, "0"});
                n.outputs.push_back({0, "Pressed", PinKind::Data, DataType::Bool, ""});
                break;
        }
    }
};

} // namespace vscript
} // namespace td
