// =============================================================================
// TD Engine - Voxel Chunk System (Tier 2.3)
//
// Streaming voxel world for the Minecraft-style target. Inspired by Zylann's
// godot_voxel module and the Unity community pattern (SubScene streaming +
// Mesh.CombineMeshes).
//
// Architecture:
//   - The world is divided into fixed-size CUBIC chunks (default 16x16x16
//     voxels). Each chunk stores an array of block IDs (1 byte per block =
//     256 distinct block types, enough for Minecraft-like + modded content).
//   - Chunks are addressed by integer (cx, cy, cz) coordinates. A ChunkMap
//     holds the live chunks in a hash table keyed by packed (cx,cy,cz).
//   - A ChunkStreamer manages load/unload around a "focus point" (usually
//     the player). Chunks outside the render distance are unloaded; chunks
//     inside are loaded from disk (or generated by a TerrainGenerator on
//     first encounter).
//   - A ChunkMesher turns the voxel array into a renderable mesh. The
//     default mesher is "naive" (one quad per visible block face); a
//     greedy mesher is TODO (Tier 3.8).
//
// Status: SKELETON. The data structures + interfaces are defined so the
// editor and the WASM bridge can compile against them. The actual meshing
// + streaming + threading are tracked as Tier 2.3 in
// docs/MODULARITY_ROADMAP.md.
//
// The skeleton is enough to support a single in-memory chunk that you can
// set/get blocks on, then render via MeshRenderer. The streaming + terrain
// generation + greedy meshing are the hard parts that come later.
// =============================================================================
#pragma once
#include "../ecs/world.h"
#include "../ecs/component.h"
#include "../core/logger.h"
#include "../core/math/vec3.h"
#include <cstdint>
#include <cstring>

namespace td {

constexpr int VOXEL_CHUNK_SIZE = 16;       // 16^3 = 4096 blocks per chunk
constexpr int VOXEL_MAX_BLOCK_TYPES = 256; // 1 byte per block ID

// Block ID 0 = air (empty). Block IDs 1-255 are app-defined (1=stone,
// 2=dirt, 3=grass, ...). The mapping is loaded from a block registry
// (TODO Tier 2.3) which holds each block's texture coords + properties.
using BlockId = uint8_t;
constexpr BlockId BLOCK_AIR = 0;

// A chunk is a fixed-size cube of voxels. Each chunk owns its data array
// (4096 bytes). For a 16-chunk render distance, total memory is
// (2*16+1)^3 * 4096 bytes = ~83MB. Acceptable for desktop; for WASM we
// shrink the render distance to keep memory under 64MB.
struct Chunk {
    int32_t cx, cy, cz;              // chunk-space coordinates
    BlockId blocks[VOXEL_CHUNK_SIZE * VOXEL_CHUNK_SIZE * VOXEL_CHUNK_SIZE];
    bool    dirty = true;            // re-mesh on next render
    bool    generated = false;       // false until TerrainGenerator runs

    Chunk() : cx(0), cy(0), cz(0) {
        std::memset(blocks, 0, sizeof(blocks));  // start as all-air
    }

    BlockId getBlock(int lx, int ly, int lz) const {
        if (lx < 0 || lx >= VOXEL_CHUNK_SIZE) return BLOCK_AIR;
        if (ly < 0 || ly >= VOXEL_CHUNK_SIZE) return BLOCK_AIR;
        if (lz < 0 || lz >= VOXEL_CHUNK_SIZE) return BLOCK_AIR;
        return blocks[(ly * VOXEL_CHUNK_SIZE + lz) * VOXEL_CHUNK_SIZE + lx];
    }

    void setBlock(int lx, int ly, int lz, BlockId b) {
        if (lx < 0 || lx >= VOXEL_CHUNK_SIZE) return;
        if (ly < 0 || ly >= VOXEL_CHUNK_SIZE) return;
        if (lz < 0 || lz >= VOXEL_CHUNK_SIZE) return;
        blocks[(ly * VOXEL_CHUNK_SIZE + lz) * VOXEL_CHUNK_SIZE + lx] = b;
        dirty = true;
    }

    // Convert a world-space position to chunk coords + local coords.
    static void worldToChunk(float wx, float wy, float wz,
                             int32_t& outCx, int32_t& outCy, int32_t& outCz,
                             int& outLx, int& outLy, int& outLz) {
        outCx = (int32_t)floorf(wx / VOXEL_CHUNK_SIZE);
        outCy = (int32_t)floorf(wy / VOXEL_CHUNK_SIZE);
        outCz = (int32_t)floorf(wz / VOXEL_CHUNK_SIZE);
        outLx = (int)wx - outCx * VOXEL_CHUNK_SIZE; if (outLx < 0) outLx += VOXEL_CHUNK_SIZE;
        outLy = (int)wy - outCy * VOXEL_CHUNK_SIZE; if (outLy < 0) outLy += VOXEL_CHUNK_SIZE;
        outLz = (int)wz - outCz * VOXEL_CHUNK_SIZE; if (outLz < 0) outLz += VOXEL_CHUNK_SIZE;
    }
};

// A hash table of live chunks. Key is packed (cx, cy, cz) into a 64-bit int.
// Open-addressing with linear probing; load factor kept under 0.7.
//
// We hand-roll the hash table to keep STL out of the voxel hot path. The
// existing ECS uses raw arrays for the same reason.
class ChunkMap {
public:
    ChunkMap(int capacity = 256) {
        m_cap = capacity;
        m_slots = new Slot[m_cap];
        m_count = 0;
    }
    ~ChunkMap() { delete[] m_slots; }

    Chunk* get(int32_t cx, int32_t cy, int32_t cz) {
        uint64_t key = packKey(cx, cy, cz);
        uint64_t mask = m_cap - 1;
        uint64_t i = hash(key) & mask;
        for (int probes = 0; probes < m_cap; probes++) {
            if (!m_slots[i].occupied) return nullptr;
            if (m_slots[i].key == key) return &m_slots[i].chunk;
            i = (i + 1) & mask;
        }
        return nullptr;
    }

    Chunk* getOrCreate(int32_t cx, int32_t cy, int32_t cz) {
        if (m_count * 10 >= m_cap * 7) resize(m_cap * 2);
        uint64_t key = packKey(cx, cy, cz);
        uint64_t mask = m_cap - 1;
        uint64_t i = hash(key) & mask;
        for (int probes = 0; probes < m_cap; probes++) {
            if (!m_slots[i].occupied) {
                m_slots[i].occupied = true;
                m_slots[i].key = key;
                m_slots[i].chunk = Chunk();
                m_slots[i].chunk.cx = cx;
                m_slots[i].chunk.cy = cy;
                m_slots[i].chunk.cz = cz;
                m_count++;
                return &m_slots[i].chunk;
            }
            if (m_slots[i].key == key) return &m_slots[i].chunk;
            i = (i + 1) & mask;
        }
        return nullptr;  // table full (shouldn't happen due to resize above)
    }

    bool remove(int32_t cx, int32_t cy, int32_t cz) {
        uint64_t key = packKey(cx, cy, cz);
        uint64_t mask = m_cap - 1;
        uint64_t i = hash(key) & mask;
        for (int probes = 0; probes < m_cap; probes++) {
            if (!m_slots[i].occupied) return false;
            if (m_slots[i].key == key) {
                m_slots[i].occupied = false;
                m_count--;
                // Re-insert subsequent entries to maintain probe sequence.
                // Standard open-addressing deletion.
                uint64_t j = (i + 1) & mask;
                while (m_slots[j].occupied) {
                    Slot s = m_slots[j];
                    m_slots[j].occupied = false;
                    m_count--;
                    uint64_t k = hash(s.key) & mask;
                    while (m_slots[k].occupied) k = (k + 1) & mask;
                    m_slots[k] = s;
                    m_slots[k].occupied = true;
                    m_count++;
                    j = (j + 1) & mask;
                }
                return true;
            }
            i = (i + 1) & mask;
        }
        return false;
    }

    int size() const { return m_count; }

private:
    struct Slot {
        bool    occupied = false;
        uint64_t key = 0;
        Chunk   chunk;
    };

    static uint64_t packKey(int32_t cx, int32_t cy, int32_t cz) {
        // Pack 3 signed 21-bit values into 63 bits (enough for +/- 1M chunks
        // per axis, = 16M blocks per axis, way beyond any practical world).
        uint64_t ux = (uint32_t)cx & 0x1FFFFF;
        uint64_t uy = (uint32_t)cy & 0x1FFFFF;
        uint64_t uz = (uint32_t)cz & 0x1FFFFF;
        return (ux << 42) | (uy << 21) | uz;
    }
    static uint64_t hash(uint64_t k) {
        // FNV-1a 64-bit. Good distribution for spatial keys.
        k ^= k >> 33;
        k *= 0xff51afd7ed558ccdULL;
        k ^= k >> 33;
        k *= 0xc4ceb9fe1a85ec53ULL;
        k ^= k >> 33;
        return k;
    }
    void resize(int newCap) {
        Slot* old = m_slots; int oldCap = m_cap;
        m_slots = new Slot[newCap];
        m_cap = newCap;
        m_count = 0;
        for (int i = 0; i < oldCap; i++) {
            if (old[i].occupied) {
                // Re-insert.
                uint64_t mask = m_cap - 1;
                uint64_t j = hash(old[i].key) & mask;
                while (m_slots[j].occupied) j = (j + 1) & mask;
                m_slots[j] = old[i];
                m_count++;
            }
        }
        delete[] old;
    }

    Slot*  m_slots = nullptr;
    int    m_cap   = 0;
    int    m_count = 0;
};

// TerrainGenerator: produces block IDs for a chunk on first encounter.
// Default impl is flat ground (y=0 = grass, y<0 = stone, y>0 = air).
// Override by registering a custom generator (TODO Tier 2.3).
class TerrainGenerator {
public:
    virtual ~TerrainGenerator() = default;
    virtual void generate(Chunk& c) {
        // Default: grass at ly=0, dirt at ly<0, stone at ly<-3, air above.
        for (int lz = 0; lz < VOXEL_CHUNK_SIZE; lz++) {
            for (int lx = 0; lx < VOXEL_CHUNK_SIZE; lx++) {
                for (int ly = 0; ly < VOXEL_CHUNK_SIZE; ly++) {
                    int worldY = c.cy * VOXEL_CHUNK_SIZE + ly;
                    BlockId b = BLOCK_AIR;
                    if (worldY == 0) b = 3;       // grass
                    else if (worldY < 0 && worldY > -4) b = 2;  // dirt
                    else if (worldY <= -4) b = 1; // stone
                    c.blocks[(ly * VOXEL_CHUNK_SIZE + lz) * VOXEL_CHUNK_SIZE + lx] = b;
                }
            }
        }
        c.generated = true;
        c.dirty = true;
    }
};

// ChunkStreamer: loads/unloads chunks around a focus point (usually the
// player's position). Single-threaded in this skeleton; the real impl
// (TODO Tier 2.3) generates + meshes chunks on worker threads, then
// uploads to the GPU on the main thread.
class ChunkStreamer {
public:
    ChunkStreamer(int renderDistance = 8)
        : m_renderDistance(renderDistance) {}

    void setGenerator(TerrainGenerator* g) { m_generator = g; }

    // Call once per frame with the player's position. Loads chunks within
    // the render distance, unloads chunks outside (with a 2-chunk hysteresis
    // to avoid thrash at the boundary).
    void update(float focusX, float focusY, float focusZ) {
        int32_t ccx = (int32_t)floorf(focusX / VOXEL_CHUNK_SIZE);
        int32_t ccy = (int32_t)floorf(focusY / VOXEL_CHUNK_SIZE);
        int32_t ccz = (int32_t)floorf(focusZ / VOXEL_CHUNK_SIZE);

        // Load pass: ensure all chunks in render distance exist.
        for (int dz = -m_renderDistance; dz <= m_renderDistance; dz++) {
            for (int dy = -m_renderDistance; dy <= m_renderDistance; dy++) {
                for (int dx = -m_renderDistance; dx <= m_renderDistance; dx++) {
                    if (dx*dx + dy*dy + dz*dz > m_renderDistance * m_renderDistance) continue;
                    Chunk* c = m_chunks.getOrCreate(ccx + dx, ccy + dy, ccz + dz);
                    if (c && !c->generated && m_generator) {
                        m_generator->generate(*c);
                    }
                }
            }
        }
        // Unload pass: remove chunks outside (render distance + hysteresis).
        // For the skeleton we skip this — a full impl walks the live set
        // and removes anything outside (rd + 2) chunks from the focus.
        // Doing this efficiently requires tracking the live set in a list,
        // not just the hash table. TODO Tier 2.3.
    }

    ChunkMap& chunks() { return m_chunks; }
    const ChunkMap& chunks() const { return m_chunks; }

    int renderDistance() const { return m_renderDistance; }

private:
    ChunkMap           m_chunks;
    int                m_renderDistance;
    TerrainGenerator*  m_generator = nullptr;
};

} // namespace td
